import { NOTIFICATIONS_ACTIONS } from "../../../../../App/Reducers/Notifications/actions";


const FORGOT_PASSWORD_REDIRECT_ACTIONS = {
  
    
    
    SET_NOTIFICATION_GLOBAL:NOTIFICATIONS_ACTIONS.SET_NOTIFICATION_GLOBAL
}




export default  FORGOT_PASSWORD_REDIRECT_ACTIONS
